version: '3.4'

networks:
  dev:
    driver: bridge 

services:
  auto_blog-service:
    depends_on:
      - "auto_blog_db"
    container_name: customer-service
    ports:
      - "5050:80"
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - dev

  auto_blog_db:
    image: postgres:latest
    container_name: auto_blog_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123123
      - POSTGRES_DB=Auto_Blog
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - Auto_Blog_data:/var/lib/postgresql/data/ 
    networks:
      - dev

volumes:
  Auto_Blog_data: